create schema dq;
alter schema dq owner to bank;

-- 流程模板
create table dq.workflow_template
(
    id          integer      not null primary key generated by default as IDENTITY,
    name        varchar(100) not null,   -- 名称
    description text,                    -- 描述
    status      smallint  default 0,     -- 状态(预留)
    create_time timestamp default now(), -- 创建时间
    update_time timestamp default now()  -- 更新时间
);

-- 流程模板节点
create table dq.template_node
(
    id                integer      not null primary key generated by default as IDENTITY,
    name              varchar(100) not null, -- 名称
    description       text,                  -- 描述
    approver_identity integer[] default [],  -- 审批者的标识(根据approver_type决定是哪种)
    approver_type     smallint,              -- role或者user
    template_id       integer      not null, -- 对应的workflow_template表id
    status            smallint  default 0,   --状态(预留)
    create_time       timestamp default now(),
    update_time       timestamp default now()
);

-- 流程模板节点间的连接
create table dq.template_node_link
(
    id              integer  not null primary key generated by default as IDENTITY,
    origin_node_id  integer  not null default 0, -- 来源节点id
    target_node_id  integer  not null default 0, -- 目标节点id
    condition_type  smallint not null,           -- 条件类型
    additional_info text,                        -- 根据condition_type的不同有不同的额外信息
    template_id     integer  not null,           -- 对应的workflow_template表id
    create_time     timestamp         default now(),
    update_time     timestamp         default now()
);

-- 流程实例（每个课题会有一个）
create table dq.workflow_instance
(
    id              integer not null primary key generated by default as IDENTITY,
    template_id     integer not null,    -- 对应的workflow_template表id
    create_user_id  integer   default 0, -- 创建者id
    status          smallint  default 0, -- 状态(流转中，已结束等等)
    current_node_id integer   default 0, -- 当前流程节点id

    create_time     timestamp default now(),
    update_time     timestamp default now()
);


